baseurl: '/nypl-design-toolkit'

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

collections:
  sections:
    output: true
  resources:
    output: true

exclude:
  - Gemfile
  - README.md
